package es.cesur.progprojectpok.clases;

public enum EstPersitentesEnum {
    PARALIZADO, QUEMADO, ENVENENADO, GRAV_ENVENENADO, DORMIDO, CONGELADO, HELADO, SOMNOLIENTO, POKERUS, DEBILITADO, SALUDABLE
}
